name: Cypress API Tests
on: [push]
jobs:
  cypress-run:
    name: Build Cypress Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install NPM Dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v5
      - name: Create merged-report Directory
        run: mkdir cypress/merged-report/
      - name: Merge mochawesome jsons in one file
        run: npx mochawesome-merge --reportDir cypress/results > cypress/merged-report/merged-report.json
      - name: Generate mochawesome html report
        run: npx marge cypress/merged-report/merged-report.json -o cypress/mochawesome-html-report