name: Cypress API Tests
on: [push]
jobs:
  cypress-run:
    name: Build Cypress Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install NPM Dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v5
      - run:
          name: Create merged-report Directory
          command: mkdir cypress/merged-report/
      - run:
          name: Merge mochawesome jsons in one file
          when: always
          command: npx mochawesome-merge --reportDir cypress/results > cypress/merged-report/merged-report.json
      - run:
          name: Generate mochawesome html report
          when: always
          command: npx marge cypress/merged-report/merged-report.json -o cypress/mochawesome-html-report
      - store_artifacts:
          name: Uploading mochawesome-merged-report.json
          path: cypress/merged-report
      - store_artifacts:
          name: Uploading mochawesome-html-report
          path: cypress/mochawesome-html-report